<?php

namespace Hgs\Openapi;

use Hgs\Openapi\Command\RefreshAccessToken;
use Illuminate\Filesystem\Filesystem;
use Illuminate\Support\Collection;
use Illuminate\Support\ServiceProvider;

class OpenapiServiceProvider extends ServiceProvider
{
    public function boot(Filesystem $filesystem)
    {
        $this->publishes([
            __DIR__ . '/../database/migrations/create_oauth_client_access_token.php' => $this->getMigrationFileName($filesystem),
        ], 'migrations');

        $this->commands([
            RefreshAccessToken::class
        ]);
    }

    protected function getMigrationFileName(Filesystem $filesystem): string
    {
        $timestamp = date('Y_m_d_His');

        return Collection::make($this->app->databasePath() . DIRECTORY_SEPARATOR . 'migrations' . DIRECTORY_SEPARATOR)
            ->flatMap(function ($path) use ($filesystem) {
                return $filesystem->glob($path . '*_create_oauth_client_access_token.php');
            })->push($this->app->databasePath() . "/migrations/{$timestamp}_create_oauth_client_access_token.php")
            ->first();
    }

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }

}
